### ISSUE TITLE
using helm flag "--set udev.enabled=true" get error

### ISSUE THREAD

**Issue by alan0415** [deislabs/akri#122]
**Describe the bug**
When I set flag "--set udev.enabled=true" in helm command to modify configuration, I get error message:
```
Error: UPGRADE FAILED: YAML parse error on akri/templates/udev.yaml: error converting YAML to JSON: yaml: line 10: could not find expected ':'
```

**Output of `kubectl get pods,akrii,akric -o wide`**
```
NAME                                              READY   STATUS    RESTARTS   AGE    IP            NODE          NOMINATED NODE   READINESS GATES
pod/akri-controller-deployment-5b4bb5cbb5-lgqq6   1/1     Running   0          167m   10.42.0.8     raspberrypi   <none>           <none>
pod/akri-agent-daemonset-krkhr                    1/1     Running   0          119m   192.168.0.9   rpi-3         <none>           <none>
pod/akri-agent-daemonset-wmhdn                    1/1     Running   0          118m   192.168.0.8   raspberrypi   <none>           <none>

NAME                               CAPACITY   AGE
configuration.akri.sh/akri-onvif   1          119m
```
**Kubernetes Version: [e.g. Native Kubernetes 1.19, MicroK8s 1.19, Minikube 1.19, K3s]**
K3s
```
NAME          STATUS   ROLES    AGE   VERSION
raspberrypi   Ready    master   10h   v1.19.3+k3s2
rpi-3         Ready    <none>   9h    v1.19.3+k3s2
```
**To Reproduce**
Install or upgrade Akri with the Helm command:
```
helm upgrade akri akri-helm-charts/akri-dev --set onvif.enabled=true --set udev.enabled=true
```

**Additional context**

**Comment by kate-goldenring** [comment]
Hi @alan0415. If you do not specify a udev rule, the udev configuration will fail to build, since it does not have any way of knowing what to search for. Maybe we can find away to make this error more descriptive. Please refer to the [udev Configuration](https://github.com/deislabs/akri/blob/main/docs/udev-configuration.md) document to learn more about using the udev Configuration and choosing a udev rule.
