### ISSUE TITLE
How do nodes other than the node of the device be added to the node list

### ISSUE THREAD

**Issue by zzhzzhzz** [deislabs/akri#165]
When an agent on a Node finds and registers an instance and puts this node under the Node list, how do other nodes add to the node list? I did not see the function used by the agent to list node in the node list whose slot was not fully full. I saw that in the previous problems, it was mentioned that instance actively included node in the Node list, so how this step was completed, or I could say that I could not clearly understand this part of the work. Another question is whether lock should be considered if two agents find that there will be duplicate instances of one device

**Comment by bfjelds** [comment]
I'm not certain I understand your question, but I'll do my best :)

The instance serves as the source of truth.

For unshared instances (like devices connected over USB and exposed through udev), even ones sharing a common udev path (i.e. nodeA /dev/video1 and nodeB /dev/video1), separate instances will be created for each node (instanceA for nodeA and instanceB for nodeB).  In this case, only nodeA will update instanceA and only nodeB will update instanceB.

For a shared instance (like ip cameras), the agent running on each node should update the instance's node list.  So, if the agents on nodeA and nodeB both see instanceA, each one should update instanceA.  Kubernetes' backend data store, etcd or whatever, should provide the locking required to ensure that simultaneous instance updates are not allowed (typically, one node would succeed and the other would get a conflict error ... the failing node should refresh its instance and try again to update it).

Does that help clarify?

**Comment by zzhzzhzz** [comment]
So can I assume that high availability via slots is invalid for non-shared instances？

**Comment by zzhzzhzz** [comment]
Well，for shared instances, such as Node A, the instance has been found and the configuration file for that instance is in the ETCD. When Node B finds the device, it first checks to see if there is instance in the instance map in the ETCD. If so, interact directly with the instance file in the etcd or something else; if not, add a new instance. Is that what you mean？

**Comment by zzhzzhzz** [comment]
So can I assume that high availability via slots is invalid for non-shared instances？

**Comment by bfjelds** [comment]
> Well，for shared instances, such as Node A, the instance has been found and the configuration file for that instance is in the ETCD. When Node B finds the device, it first checks to see if there is instance in the instance map in the ETCD. If so, interact directly with the instance file in the etcd or something else; if not, add a new instance. Is that what you mean？

Essentially.  This is one of the things that the Instance CRD exists to provide.

**Comment by bfjelds** [comment]
> So can I assume that high availability via slots is invalid for non-shared instances？

Our default deployment model for brokers is like a DaemonSet.  So, for any instance, bounded by the Configuration.Capacity, we deploy 1 broker to every Node that can see the Instance.

For a shared Configuration, multiple Nodes can see the same Instance.  Because of that, multiple brokers are deployed if multiple Nodes can see the Instance.  This provides high availability.

For a non-shared Configuration, only one Node can see any Instance.  Because of that, and our DaemonSet deployment, one broker is deployed.  You are correct that this does not provide high availability.  As a workaround, if the Configuration.Capacity is configured to be greater than 1, you can manually deploy (by creating and `kubectl apply` a PodSpec targeting the instance) another broker to the Node and create high availability.

We are working on the idea of [providing different deployment concepts](https://github.com/deislabs/akri/blob/main/docs/proposals/broker-deployment-strategies.md), one that we've talked about would follow more of a Deployment (with replicas) strategy.  With that strategy, the scheduler would create X replicas of the broker wherever it could.  This would provide high availability for shared and non-shared Configurations.

**Comment by zzhzzhzz** [comment]
> > So can I assume that high availability via slots is invalid for non-shared instances？
> 
> Our default deployment model for brokers is like a DaemonSet. So, for any instance, bounded by the Configuration.Capacity, we deploy 1 broker to every Node that can see the Instance.
> 
> For a shared Configuration, multiple Nodes can see the same Instance. Because of that, multiple brokers are deployed if multiple Nodes can see the Instance. This provides high availability.
> 
> For a non-shared Configuration, only one Node can see any Instance. Because of that, and our DaemonSet deployment, one broker is deployed. You are correct that this does not provide high availability. As a workaround, if the Configuration.Capacity is configured to be greater than 1, you can manually deploy (by creating and `kubectl apply` a PodSpec targeting the instance) another broker to the Node and create high availability.
> 
> We are working on the idea of [providing different deployment concepts](https://github.com/deislabs/akri/blob/main/docs/proposals/broker-deployment-strategies.md), one that we've talked about would follow more of a Deployment (with replicas) strategy. With that strategy, the scheduler would create X replicas of the broker wherever it could. This would provide high availability for shared and non-shared Configurations.

Ok, I see. Thanks for your reply.
