### ISSUE TITLE
Naming guidelines

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#199]
**Is your feature request related to a problem? Please describe.**

Naming guidelines would be useful if documented if desired.

For example:

+ `akri-agent-daemonset`
+ `akri-controller-deployment`

Is this guidance `akri-[THING]-[TYPE]`?

It is a common pattern with Kubernetes but I find it overwrought since these objects all have Kinds (and Labels) and e.g.: `kubectl get deployment/akri-controller-deployment` is redundant and leads to lengthy names

**Is your feature request related to a way you would like Akri extended? Please describe.**

**Describe the solution you'd like**

Definitive naming guidelines

**Describe alternatives you've considered**

**Additional context**

**Comment by bfjelds** [comment]
The existing convention is certainly redundant.  I think it happened fairly organically, without much debate.

I would be totally open to debating/simplifying/documenting the naming convention.

**akri-[THING]-[TYPE]**
* `akri`: this seems important to reduce the chances of naming collisions
* `[THING]`: this seems important just for identifying components
* `[TYPE]`: this seems purely redundant and I can't think of a benefit.  I suspect it came to be ONLY because it clarified the various deployment yaml names.  Can anyone think of a benefit for this?

I would be happy to simplify to **akri-[THING]**.

**Comment by DazWilkin** [comment]
There are namespaces of course and Akri could e.g. be deployed to a namespace `akri` and the daemonset could then just be called `agent` but, I think the prefixing `akri-` is a good compromise.

I will try today deploying Akri to the non-default namespace.

Since I highlighted the *issue*, I'll take the action to document the solution :-)

**Comment by DazWilkin** [comment]
Went with creating a proposal (https://github.com/deislabs/akri/pull/204)
