### ISSUE TITLE
Synchronise (?) Kubernetes and crictl

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#245]
**Is your feature request related to a problem? Please describe.**

It's unclear but it appears (!?) that cri-tools (including `crictl`) are version-sync'd with Kubernetes:

https://github.com/kubernetes-sigs/cri-tools/tags

The E2E test runner has been using `crictl` v1.17.0 for all (>=1.18) versions of Kubernetes:

+ https://github.com/deislabs/akri/blob/fd2ed66c30c9fe4a7820a9b2feecfd3420da717e/.github/workflows/run-test-cases.yml#L170
+ https://github.com/deislabs/akri/blob/fd2ed66c30c9fe4a7820a9b2feecfd3420da717e/.github/workflows/run-test-cases.yml#L225

Confirm whether Kubernetes and crictl are version-sync'd and then decide whether to apply this to the E2E tests.

**Comment by bfjelds** [comment]
According to https://github.com/kubernetes-sigs/cri-tools, it looks like versions between 1.11 and 1.15 are aligned, but maybe that 1.16 and above should all work together.

Our tests do this:
* Microk8s v1.16 & v1.17 => crictl v1.16 ... otherwise crictl v1.17
* K3s v1.16 & v1.17 => crictl v1.16 ... otherwise crictl v1.17
* K8s => use crictl that aligns to version

Our docs demonstrate installing:
* k3s (most recent version) with crictl v1.17
* microk8s (v1.19) with crictl v1.17
* for k8s, no install for crictl needed

From this, it seems our tests align to our documentation.  We can probably afford to assume this is a happy path until someone has a need to try some specific version of crictl and finds it doesn't work.
